sudo: required
services:
  - docker
  - docker-compose
script:
  - DB_PASSWORD=password docker-compose up backend
  - exit $(docker inspect -f '{{ .State.ExitCode }}' `docker-compose ps -q backend`)
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: npm
  api_key: $NPM_API_KEY
  on:
    branch: master
