version: '2'

services:
  db:
    image: arangodb/arangodb
    ports:
      - ${DB_EXTERNAL_PORT}:8529
    command: arangod
    environment:
      ARANGO_ROOT_PASSWORD: ${DB_PASSWORD}

  backend:
    build: .
    ports:
      - 3001:3000
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    network_mode: host
    environment:
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: localhost
      DB_PORT: ${DB_EXTERNAL_PORT}
      TERM: xterm-256color
